language: python
sudo: false
branches:
    only:
      - master
python:
  - "3.5"
cache: pip
install:
  - pip install tox
  - pip install codecov
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
  - TOX_ENV=docs
script:
  - tox -e $TOX_ENV
